version: '3'

services:
  web:
    build:
      context: ./api-nexthouse
      args:
        - DATABASE_URL=mysql://root:nexthouse@database/nexthouse
        - HASH_KEY=768d04fdd9caf9191aae594e5edd1bcefb60bfd847effa0995c8ec4ba67caced
    working_dir: /app
    ports:
      - 3001:3001
    links:
      - database
    depends_on:
      - database
    networks:
      - api
  database:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=nexthouse
      - MYSQL_DATABASE=nexthouse
    networks:
      - api
networks:
  api:
    ipam:
      driver: default