version: '3'

services:
  web:
    build:
      context: ./nexthouse
      args:
        - REACT_APP_API=http://api:3001/api/v1
    ports:
      - 3000:3000
    links:
      - api
    networks:
      - api
  api:
    build:
      context: ./api-nexthouse
      args:
        - DATABASE_URL=mysql://root:nexthouse@database/nexthouse
        - HASH_KEY=768d04fdd9caf9191aae594e5edd1bcefb60bfd847effa0995c8ec4ba67caced
        - NODE_ENV=test
    working_dir: /app
    ports:
      - 3001:3001
    links:
      - database
    networks:
      - api
      - db
  database:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=nexthouse
      - MYSQL_DATABASE=nexthouse
    networks:
      - db
networks:
  api:
    ipam:
      driver: default
  db:
    ipam:
      driver: default