version: '3'

services:
  web:
    build:
      context: ./neohouse
    ports:
      - 3000:3000
    links:
      - api
  api:
    build:
      context: ./api-neohouse
      args:
        - DATABASE_URL=mysql://root:neohouse@database/neohouse
        - HASH_KEY=768d04fdd9caf9191aae594e5edd1bcefb60bfd847effa0995c8ec4ba67caced
        - NODE_ENV=test
    working_dir: /app
    ports:
      - 3001:3001
    links:
      - database
  database:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=neohouse
      - MYSQL_DATABASE=neohouse